### ISSUE TITLE
xubuntu wants liboctave-dev

### ISSUE THREAD

**Issue by AndreiCherniaev** [apjanke/octave-tablicious#101]
I want to install pack using [instruction](https://github.com/apjanke/octave-tablicious) "Quick start".

But I got error: 
_error: pkg: please install the Debian package "liboctave-dev" to get the mkoctfile command
error: called from
    __gripe_missing_component__ at line 60 column 3
    configure_make at line 50 column 7
    install at line 198 column 7
    pkg at line 568 column 9_

https://github.com/apjanke/octave-tablicious/blob/47c74fefe2157942230c03bb6d990dc702b227ac/dev-tools/install-octave-4.2-ubuntu.sh#L11

**Comment by apjanke** [comment]
Looks like you're running in to an issue with how Octave is packaged in the Debian Linux distro and its derivatives like Ubuntu. You need the Octave development tools package in order to install Octave packages that require compiling native extensions like octfiles, and Tablicious is one of those. GNU Octave itself doesn't really make that distinction, but it looks like Debian is splitting it out in to a separate package.

This is done with the `apt` command at the OS level (in a shell) and not from Octave itself. Please try running this command in a shell:

```
apt install liboctave-dev
```

You may need to prefix it with `sudo`, like this:

```
sudo apt install liboctave-dev
```

If that fixes this problem for you, please let me know here, and I'll add this step to that "Quick start" README section and try to fix up our `install-octave-*-ubuntu.sh` files.

**Comment by apjanke** [comment]
Oh, actually: did you run that `install-octave-4.2-ubuntu.sh` script?  That is a shell script that will try to take care of this problem for you. You need to run it yourself from a shell (and not Octave); it's not something that is called automatically by Octave or its `pkg` command.

**Comment by apjanke** [comment]
Closing bc no response, and I can't repdroduce myself.
