### ISSUE TITLE
Compatibility with Octave version 8.x.x

### ISSUE THREAD

**Issue by ghost** [apjanke/octave-tablicious#106]
Is Tablicious compatible with Octave version 8.2.0 or higher?

--------

Andrew's notes:

## TODO

* [x] Fix `'event_manager_register_doc' undefined` (doco registration)
* [x] Fix shadowing of `startsWith` and `endsWith` (#102)

**Comment by apjanke** [comment]
Hi, praschchoksi!

Tablicious's intent is to support all Octave versions from Octave 6.4.0 up through whatever the current Octave version is. (I should add a note about that to the documentation.)

But I have not actually tested Tablicious under Octave 8.x yet, since I'm still using an older Octave on my personal machines. I'm not aware of anything in particular that would cause major issues under Octave 8.x, but who knows without testing. Especially with Octave's package-management stuff like `pkg` and `PKG_ADD`. And I've got these two little things to clean up:

* https://github.com/apjanke/octave-tablicious/issues/102
* https://github.com/apjanke/octave-tablicious/issues/94

If you encounter any compatibility problems between Tablicious and Octave 8.x (or 7.x for that matter), please [post it as an issue here](https://github.com/apjanke/octave-tablicious/issues) and I'll make it a priority to fix.

Let's leave this ticket open as a reminder to me to get around to testing Tablicious under Octave 8.x. Maybe I'll have time this weekend?

**Comment by mgcooper** [comment]
@apjanke @prashchoksi 

If it's helpful, I'm running 8.3.0 and tablicious appears to work fine. Here's what I did:

- I ran "ex_01_suppliers_parts.m" without error, although it doesn't seem to use much of the package. 
- I converted a datenum array to datetime, and used a few datetime methods without error, such as "Month", "Day", and "Year".
- I ran the tests. The two datetime tests involving time zones failed (other two passed). The three duration tests passed.

That's only a sliver of the functionality, but better than  nothing. Happy to help further if you want to provide some tests or a script.

**Comment by apjanke** [comment]
Thanks, mgcooper!

> Happy to help further if you want to provide some tests or a script.

Uhh, writing some more tests, especially some more thorough unit tests, is on my to-do list here. What you ran is what I've got for you at the moment.

Leaving this ticket open until I can play around with Tablicious under Octave 8.x myself and better confirm this. Hopefully with some additional tests.

**Comment by roger-noss** [comment]
Aside from shadowing warnings by endsWith.m and startsWith.m when installing via 'pkg load -forge tablicious', I encountered:

error: '__event_manager_register_doc__' undefined near line 41, column 7
error: called from
    load_tablicious at line 41 column 7
    C:\Users\roger\AppData\Roaming\octave\api-v58\packages\tablicious-0.3.6\PKG_ADD at line 3 column 1
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

Perhaps it is useful to you.
Windows 11, version 8.3.0

**Comment by apjanke** [comment]
That is useful, roger-noss. Looks like the (semi-documented) API for registering documents with Octave's graphical help browser has changed. Going to have to add in some conditionalization there, I think.

Updating the main description on this ticket with a couple specific TODOs.

**Comment by apjanke** [comment]
I think this is all fixed on the `main` branch. (Except for the username-in-spaces thing; that'll be harder.) A Tablicious 0.4.0 release with the fixes will be coming soon.

If you want to test this out ahead of time, you can clone the repo or download a copy of its contents from GitHub, and add its `inst/` directory to your Octave path. That should get everything except the `datetime` time zone conversions working. It's working for me under Octave 8.4.0 on macOS that way.

**Comment by apjanke** [comment]
Closing this ticket as Fixed since it's all merged to `main` and seems to be working. If you run in to any further Octave 8.x compatibility problems, feel free to reopen this ticket.
